import * as M from './model.mjs';
const $=s=>document.querySelector(s);
const create=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
const download=(name,text,type='text/csv')=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=create('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const page=new URLSearchParams(location.search).get('demo')||'variants';
const names={variants:['01 / CATALOG ENGINEERING','Every variant. Every price.','A one-product pilot for complex catalogs. Explore 315 size, material, and design combinations, then inspect every quantity break.'],reports:['02 / REPORT OPERATIONS','A report, on your terms.','Select a report and output format. Inspect the same deterministic fixtures in CSV, pipe-delimited, or tab-delimited form.'],calls:['03 / SERVICE OPERATIONS','A missed call. A clear next step.','Walk through a synthetic missed-call conversation, qualification, opt-out, and lead logging without contacting anyone.'],approval:['04 / HUMAN-REVIEWED AUTOMATION','Good leads need good judgment.','Inspect the evidence behind a score, record a decision, and export only approved prospects for the selected market.']};
const selected=names[page]?page:'variants';
$('#chapter').textContent=names[selected][0];$('#title').textContent=names[selected][1];$('#intro').textContent=names[selected][2];document.querySelector(`[data-page="${selected}"]`).setAttribute('aria-current','page');
function status(message,error=false){const s=$('#status');s.textContent=message;s.className='status'+(error?' error':'');}
function variantDemo(){
$('#app').innerHTML=`<div class="grid"><section class="panel hero-panel"><p class="eyebrow">SYNTHETIC PRODUCT / MADE TO ORDER</p><h2>One print. 315 possibilities.</h2><div class="paper-art" aria-hidden="true"><span>hello.</span><span>↗</span></div><div class="grid"><div><label for="size">Size</label><select id="size"></select></div><div><label for="material">Material</label><select id="material"></select></div></div><label for="design">Number of designs</label><select id="design"></select><label for="quantity">Quantity</label><input type="number" id="quantity" value="1" min="1" max="10000" step="1"><div id="status" class="status" role="status"></div></section><section class="panel"><p class="eyebrow">PRICE REVIEW / USD</p><div class="stat" id="unit"></div><span class="subtle">per unit at the selected quantity</span><div class="metrics"><div><strong id="total"></strong><span>Order total</span></div><div><strong id="sku"></strong><span>Stable variant SKU</span></div></div><div class="table-wrap"><table><thead><tr><th>Quantity</th><th>Unit price</th><th>Discount</th></tr></thead><tbody id="tiers"></tbody></table></div><div class="actions"><button id="review">Download tier review CSV</button><button class="secondary" id="shopify">Download draft product CSV</button></div><p class="subtle">315 unique variants · 1,260 review rows · integer-cent arithmetic</p></section></div>`;
for(const [id,values] of [['size',M.sizes],['material',M.materials],['design',M.designs]])for(const value of values)$('#'+id).append(new Option(value,value));
const render=()=>{try{const args=[$('#size').value,$('#material').value,$('#design').value];const q=M.quote(...args,Number($('#quantity').value));$('#unit').textContent=money(q.unit);$('#total').textContent=money(q.total);$('#sku').textContent=q.sku;$('#tiers').replaceChildren(...M.tiers.map(t=>{const row=create('tr',undefined,t.min===q.tier?'active':'');row.append(create('td',t.min+'+'),create('td',money(M.quote(...args,t.min).unit)),create('td',(100-t.factor)+'%'));return row;}));status('Valid variant. Highest eligible quantity tier applied.');}catch(e){$('#unit').textContent='—';$('#total').textContent='—';status(e.message,true);}};
for(const id of ['size','material','design','quantity'])$('#'+id).addEventListener('input',render);
$('#review').onclick=()=>download('variant-tier-review.csv',M.variantReview());$('#shopify').onclick=()=>download('sample-product-draft.csv',M.shopifyDraft());render();
$('#limitations').textContent='Unsolicited independent concept. Prices are illustrative, not client prices. The product CSV is a draft for review and has not been imported into Shopify. Quantity tiers require a separately verified pricing app or implementation; this preview does not configure checkout.';
}
function reportDemo(){
$('#app').innerHTML=`<div class="grid"><section class="panel"><p class="eyebrow">REPORT DEFINITION</p><h2>Configure once. Run deliberately.</h2><label for="report">Sample report</label><select id="report"><option value="inventory">Inventory review</option><option value="aging">Order aging</option></select><label for="format">Output format</label><select id="format"><option value="csv">CSV</option><option value="pipe">Pipe-delimited</option><option value="tsv">Tab-delimited</option></select><div class="actions"><button id="run">Run fixture report</button><button id="config" class="secondary">Download config.yml</button></div><div id="status" class="status" role="status">Ready. No database credentials required.</div><p class="subtle">Production contract: scheduled or manual job → named report → client-owned runner → retained artifact → optional email.</p><pre id="config-preview"></pre></section><section class="panel"><p class="eyebrow">ARTIFACT PREVIEW</p><h2 id="artifact">Waiting for a run</h2><pre id="output">Select a report, then run the fixture.</pre><button id="download" disabled>Download report</button><h3>Run history</h3><ol id="history" class="log"></ol></section></div>`;
let result=null;const config=()=>{$('#config-preview').textContent=M.reportConfig($('#report').value,$('#format').value);result=null;$('#download').disabled=true;$('#output').textContent='Configuration changed. Run the fixture to generate a matching artifact.';$('#artifact').textContent='Waiting for a run';};
$('#report').onchange=config;$('#format').onchange=config;$('#config').onclick=()=>download('config.yml',M.reportConfig($('#report').value,$('#format').value),'text/yaml');
$('#run').onclick=()=>{const key=$('#report').value,format=$('#format').value;result={name:`${key}.${format==='pipe'?'txt':format}`,text:M.reportFile(key,format)};$('#artifact').textContent=result.name;$('#output').textContent=result.text;$('#download').disabled=false;$('#history').prepend(create('li',`${M.reports[key].label} · ${format.toUpperCase()} · 3 fixture rows`));status('Fixture report generated. No Oracle query or email was executed.');};
$('#download').onclick=()=>{if(result)download(result.name,result.text,'text/plain');};config();
$('#limitations').textContent='Unsolicited independent concept for a scheduled-report workflow. This runs local fixtures only. Oracle SQL execution, GitLab schedules, Vault authentication, artifact retention, and SMTP must be implemented and tested in the client environment.';
}
function callDemo(){
$('#app').innerHTML=`<div class="grid"><section class="panel"><p class="eyebrow">CONVERSATION PREVIEW</p><h2>Keep the next step simple.</h2><div class="actions"><button id="missed">Simulate missed call</button><button class="secondary" id="reset">Reset demo</button></div><div id="messages"><p class="empty">Your simulated conversation starts here.</p></div><form id="reply-form"><label for="reply">Customer reply</label><input id="reply" maxlength="500" placeholder="e.g. A leaking kitchen faucet" autocomplete="off"><div class="actions"><button id="send" disabled>Preview reply</button><button type="button" id="stop" class="secondary" disabled>Simulate STOP</button></div></form><div id="status" class="status" role="status"></div></section><section class="panel hero-panel"><p class="eyebrow">LEAD RECORD / SYNTHETIC DATA</p><h2 id="stage">Waiting for a call</h2><dl><dt>Repair issue</dt><dd id="issue">—</dd><dt>Service address</dt><dd id="address">—</dd><dt>Column G · Image reference</dt><dd id="media">—</dd></dl><label for="photo">Preview image intake (test image only)</label><input id="photo" type="file" accept="image/*"><p class="subtle">Only the filename is kept. Nothing is sent to Google Drive.</p><h3>Event log</h3><ol id="log" class="log"></ol></section></div>`;
let state=M.callState();const render=()=>{const has=state.messages.length;$('#messages').replaceChildren(...state.messages.map(m=>create('div',m.text,'message '+m.side)));if(!has)$('#messages').append(create('p','Your simulated conversation starts here.','empty'));$('#stage').textContent={waiting:'Waiting for a call',issue:'Collecting repair details',address:'Collecting service address',qualified:'Ready for booking review',stopped:'Opted out'}[state.stage];$('#issue').textContent=state.issue||'—';$('#address').textContent=state.address||'—';$('#media').textContent=state.media.join(', ')||'—';$('#log').replaceChildren(...state.log.map(l=>create('li',l)));$('#send').disabled=['waiting','stopped'].includes(state.stage);$('#stop').disabled=$('#send').disabled;};
$('#missed').onclick=()=>{M.missedCall(state);render();status('Event processed locally. Click again to test duplicate handling.');};
const send=text=>{try{M.reply(state,text);render();$('#reply').value='';status('Preview updated. No SMS sent.');}catch(e){status(e.message,true);}};
$('#reply-form').onsubmit=e=>{e.preventDefault();send($('#reply').value);};$('#stop').onclick=()=>send('STOP');$('#reset').onclick=()=>{state=M.callState();$('#photo').value='';render();status('Demo reset.');};
$('#photo').onchange=()=>{const f=$('#photo').files[0];if(!f)return;try{if(!f.type.startsWith('image/'))throw new Error('Choose a test image.');M.mediaAdded(state,f.name);render();status('Image filename recorded locally.');}catch(e){status(e.message,true);}};
$('#limitations').textContent='Unsolicited independent concept. Replies follow deterministic rules, not an LLM. No Twilio, Make, booking, Sheets, or Drive account is connected. Carrier delivery timing, consent configuration, webhook verification, durable retries, and production MMS delivery remain integration work.';render();
}
function approvalDemo(){
$('#app').innerHTML=`<section class="panel"><div class="grid"><div><p class="eyebrow">CONFIGURATION, NOT HARDCODING</p><h2>One engine. Separate markets.</h2><label for="market">Market configuration</label><select id="market"><option>Cary</option><option>Wilmington</option></select></div><div><div class="metrics"><div><strong id="approved-count">0</strong><span>Approved this market</span></div><div><strong id="pending-count">0</strong><span>Awaiting a decision</span></div></div><button id="export">Export approved CSV</button><p class="subtle">Synthetic records only. A CSV preview replaces the production CRM adapter.</p></div></div><div id="status" class="status" role="status"></div></section><div id="leads" class="cards"></div><section class="panel" style="margin-top:20px"><h2>Decision trail</h2><ol id="audit" class="log"></ol></section>`;
const state=M.approvalState();const render=()=>{const market=$('#market').value;const list=M.prospects.filter(p=>p.market===market).sort((a,b)=>M.score(b,market).total-M.score(a,market).total);$('#leads').replaceChildren(...list.map(p=>{const box=create('article',undefined,'lead');const s=M.score(p,market),d=state.decisions[p.id];box.append(create('span',String(s.total),'score'),create('h3',p.name),create('p',p.domain),create('p',`Synthetic evidence: ${p.signal}. ${p.fresh?'Fresh sample signal':'Stale sample signal'}.`),create('p',`Score = sector ${s.components.sector} + market ${s.components.location} + freshness ${s.components.freshness}${p.suppressed?' (suppressed: forced to 0)':''}`),create('div',p.suppressed?'Suppressed':d?.decision||'Needs review','decision'));const label=create('label','Reviewer note');label.htmlFor='note-'+p.id;const note=create('input');note.id=label.htmlFor;note.maxLength=300;note.value=d?.note||'';box.append(label,note);const controls=create('div',undefined,'actions');for(const decision of ['approved','rejected']){const b=create('button',decision==='approved'?'Approve':'Reject',decision==='rejected'?'secondary':'');b.disabled=p.suppressed&&decision==='approved';b.onclick=()=>{M.decide(state,p.id,decision,note.value);render();status('Decision recorded in this browser tab. No outreach performed.');};controls.append(b);}box.append(controls);return box;}));$('#approved-count').textContent=list.filter(p=>state.decisions[p.id]?.decision==='approved').length;$('#pending-count').textContent=list.filter(p=>!p.suppressed&&!state.decisions[p.id]).length;$('#audit').replaceChildren(...state.audit.map(a=>create('li',`${a.id}: ${a.decision}${a.note?' — '+a.note:''}`)));};
$('#market').onchange=render;$('#export').onclick=()=>{download('approved-'+$('#market').value.toLowerCase()+'.csv',M.approvedCSV(state,$('#market').value));status('Exported approved records for the selected market only.');};render();
$('#limitations').textContent='Unsolicited independent concept using fictional organizations and evidence. Scores are transparent rules, not AI research. No data provider or CRM is connected; decisions reset on reload. Production requires provider adapters, persistent deduplication, dated evidence, authenticated review, and outcome tracking.';
}
({variants:variantDemo,reports:reportDemo,calls:callDemo,approval:approvalDemo})[selected]();
